#!/bin/bash
. /etc/openvpn/login/config.sh
Query="SELECT user_name FROM users WHERE user_name='$username' AND auth_vpn=md5('$password') AND status='live' AND is_freeze=0 AND is_ban=0 AND (duration > 0 OR vip_duration > 0 OR private_duration > 0)"
user_name=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
if [ "$user_name" != '' ] && [ "$user_name" = "$username" ]; then
    echo "user : $username"
    echo 'authentication ok.'
    exit 0
else
    . /etc/openvpn/login/test_config.sh
    user_name=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
    [ "$user_name" != '' ] && [ "$user_name" = "$username" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'authentication failed.'; exit 1
fi